abstract final class AppSVGs {
  static const mainPath = 'assets/svgs';
  static const playCircle = '$mainPath/play_circle.svg';
  static const bookmark = '$mainPath/bookmark.svg';
  static const bookmarkOutlined = '$mainPath/bookmark_outlined.svg';
  static const stars = '$mainPath/stars.svg';
  static const chat = '$mainPath/chat.svg';
  static const figma = '$mainPath/figma.svg';
  static const lock = '$mainPath/lock.svg';
  static const coupon = '$mainPath/coupon.svg';
  static const chatFilled = '$mainPath/chat_filled.svg';
  static const compass = '$mainPath/compass.svg';
  static const filter = '$mainPath/filter.svg';
  static const close = '$mainPath/close.svg';
  static const calendar = '$mainPath/calendar.svg';
  static const clock = '$mainPath/clock.svg';
  static const coins = '$mainPath/coins.svg';
  static const course = '$mainPath/course.svg';
  static const discussion = '$mainPath/discussion.svg';
  static const leaderbaord = '$mainPath/leaderboard.svg';
  static const points = '$mainPath/points.svg';
  static const store = '$mainPath/store.svg';
}
